# Generated by Django 4.1 on 2022-08-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('completed', models.BooleanField(verbose_name='Completed')),
            ],
        ),
    ]
